-- Migration: item_approval_instances + item_approval_decisions
-- Powers the approval engine for item creation workflow

DO $$ BEGIN
  CREATE TYPE approval_decision_type AS ENUM (
    'APPROVED',
    'REJECTED',
    'ESCALATED',
    'DELEGATED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE approval_instance_status AS ENUM (
    'PENDING',
    'IN_PROGRESS',   -- Approver has opened/viewed the request
    'APPROVED',
    'REJECTED',
    'ESCALATED',
    'SUPERSEDED'     -- Request was revised; this instance is no longer active
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── item_approval_instances ──────────────────────────────────────────────────
-- One record per approval task generated by the approval engine

CREATE TABLE IF NOT EXISTS item_approval_instances (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id            UUID NOT NULL REFERENCES item_requests(id) ON DELETE CASCADE,
  rule_id               UUID REFERENCES item_approval_rules(id),
  rule_name             TEXT NOT NULL,  -- Snapshot of rule name at time of creation

  -- Who needs to approve
  approver_type         TEXT NOT NULL DEFAULT 'ROLE',  -- 'ROLE' or 'USER'
  approver_role         TEXT,    -- Role name (e.g. 'MASTER_DATA_MANAGER')
  approver_user_id      UUID REFERENCES auth.users(id),  -- Set for USER type

  -- Sequential stage ordering
  stage_order           INTEGER NOT NULL DEFAULT 1,

  -- SLA
  sla_hours             INTEGER NOT NULL DEFAULT 72,
  sla_deadline          TIMESTAMPTZ,  -- Calculated on insert: created_at + sla_hours
  sla_breached          BOOLEAN NOT NULL DEFAULT false,

  -- Status
  status                approval_instance_status NOT NULL DEFAULT 'PENDING',

  -- Link to the decision (set when status transitions to APPROVED/REJECTED)
  decision_id           UUID,  -- FK to item_approval_decisions added below

  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Auto-set SLA deadline on insert
CREATE OR REPLACE FUNCTION set_approval_sla_deadline()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.sla_deadline := NEW.created_at + (NEW.sla_hours || ' hours')::interval;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_iai_sla_deadline
  BEFORE INSERT ON item_approval_instances
  FOR EACH ROW EXECUTE FUNCTION set_approval_sla_deadline();

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_iai_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_iai_updated_at
  BEFORE UPDATE ON item_approval_instances
  FOR EACH ROW EXECUTE FUNCTION update_iai_updated_at();

-- Auto-mark SLA as breached (checked by application scheduler; also set on SELECT)
CREATE OR REPLACE FUNCTION mark_sla_breached()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sla_deadline IS NOT NULL AND NOW() > NEW.sla_deadline
     AND NEW.status = 'PENDING' AND NEW.sla_breached = false THEN
    NEW.sla_breached := true;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_iai_sla_breach
  BEFORE UPDATE ON item_approval_instances
  FOR EACH ROW EXECUTE FUNCTION mark_sla_breached();

CREATE INDEX IF NOT EXISTS idx_iai_request_id ON item_approval_instances(request_id);
CREATE INDEX IF NOT EXISTS idx_iai_approver_role ON item_approval_instances(approver_role);
CREATE INDEX IF NOT EXISTS idx_iai_status ON item_approval_instances(status);
CREATE INDEX IF NOT EXISTS idx_iai_pending_sla
  ON item_approval_instances(sla_deadline)
  WHERE status = 'PENDING';

ALTER TABLE item_approval_instances ENABLE ROW LEVEL SECURITY;

-- Approvers can see instances assigned to their role
CREATE POLICY "iai_select_approver"
  ON item_approval_instances FOR SELECT
  USING (
    is_admin()
    OR has_permission('approve_item_requests')
    OR has_permission('manage_item_definition')
    OR has_permission('view_all_requests')
  );

-- Only system (SECURITY DEFINER functions) or Admin can insert
CREATE POLICY "iai_insert_system"
  ON item_approval_instances FOR INSERT
  WITH CHECK (is_admin() OR has_permission('approve_item_requests'));

-- Approvers and Admin can update status
CREATE POLICY "iai_update_approver"
  ON item_approval_instances FOR UPDATE
  USING (
    is_admin()
    OR has_permission('approve_item_requests')
  );

-- ─── item_approval_decisions ─────────────────────────────────────────────────
-- Immutable audit log of every approval action

CREATE TABLE IF NOT EXISTS item_approval_decisions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES item_approval_instances(id),
  request_id        UUID NOT NULL REFERENCES item_requests(id),

  decision          approval_decision_type NOT NULL,
  decided_by        UUID NOT NULL REFERENCES auth.users(id),
  decided_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- MANDATORY comment — minimum 10 characters
  comments          TEXT NOT NULL CHECK (LENGTH(TRIM(comments)) >= 10),

  -- Escalation/delegation target
  escalated_to_user UUID REFERENCES auth.users(id),
  escalation_reason TEXT,

  -- Context snapshot at time of decision
  request_status_at_decision  item_request_status NOT NULL,
  item_summary                JSONB  -- Snapshot of key item fields for audit completeness
);

-- Immutability: decisions are forever
CREATE OR REPLACE FUNCTION enforce_iad_immutability()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Approval decisions are immutable and cannot be modified or deleted.';
END;
$$;

CREATE TRIGGER trg_iad_no_update
  BEFORE UPDATE ON item_approval_decisions
  FOR EACH ROW EXECUTE FUNCTION enforce_iad_immutability();

CREATE TRIGGER trg_iad_no_delete
  BEFORE DELETE ON item_approval_decisions
  FOR EACH ROW EXECUTE FUNCTION enforce_iad_immutability();

-- When a decision is recorded, update the linked approval instance
CREATE OR REPLACE FUNCTION update_instance_on_decision()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  new_status approval_instance_status;
BEGIN
  -- Map decision type to instance status.
  -- DELEGATED is not a valid approval_instance_status — treat as ESCALATED
  -- because the intent (routing to another party) is the same.
  new_status := CASE NEW.decision
    WHEN 'APPROVED'   THEN 'APPROVED'::approval_instance_status
    WHEN 'REJECTED'   THEN 'REJECTED'::approval_instance_status
    WHEN 'ESCALATED'  THEN 'ESCALATED'::approval_instance_status
    WHEN 'DELEGATED'  THEN 'ESCALATED'::approval_instance_status  -- DELEGATED has no matching instance status
    ELSE 'PENDING'::approval_instance_status
  END;

  UPDATE item_approval_instances
  SET status = new_status,
      decision_id = NEW.id,
      updated_at = now()
  WHERE id = NEW.instance_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_iad_update_instance
  AFTER INSERT ON item_approval_decisions
  FOR EACH ROW EXECUTE FUNCTION update_instance_on_decision();

-- Add FK from instances to decisions now that decisions table exists
ALTER TABLE item_approval_instances
  ADD CONSTRAINT fk_iai_decision
  FOREIGN KEY (decision_id) REFERENCES item_approval_decisions(id);

CREATE INDEX IF NOT EXISTS idx_iad_instance_id ON item_approval_decisions(instance_id);
CREATE INDEX IF NOT EXISTS idx_iad_request_id ON item_approval_decisions(request_id);
CREATE INDEX IF NOT EXISTS idx_iad_decided_by ON item_approval_decisions(decided_by);

ALTER TABLE item_approval_decisions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "iad_select_permitted"
  ON item_approval_decisions FOR SELECT
  USING (
    is_admin()
    OR has_permission('approve_item_requests')
    OR has_permission('view_all_requests')
  );

-- Decisions are inserted by the approver via a SECURITY DEFINER function (not direct INSERT)
CREATE POLICY "iad_insert_approver"
  ON item_approval_decisions FOR INSERT
  WITH CHECK (
    decided_by = auth.uid()
    AND (is_admin() OR has_permission('approve_item_requests'))
  );

COMMENT ON TABLE item_approval_instances IS
  'One record per approval task per item request. Routed to a role or named user. '
  'Sequential stage_order enforced by application: stage N cannot start until stage N-1 is APPROVED.';

COMMENT ON TABLE item_approval_decisions IS
  'Immutable audit log of every approval action. Never update or delete. '
  'Linked to item_approval_instances; triggers instance status update on insert.';
